config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#about"

  resources :topics, only: [:index, :show, :new, :create, :edit, :update] do
    resources :logs, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_topic, only:%i[new create]

  def new
    @log = Log.new
  end

  def create
    @log = Log.new(log_params)
    @log.topic = @topic
    if @log.save
      redirect_to topic_path(@topic)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def log_params
    params.require(:log).permit(:as_int, :as_string, :as_text, :as_float, :as_duration, :as_boolean, :min_scale, :max_scale, :as_list)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show edit update]

  def index
    @topics = Topic.all
  end

  def show
    @log = Log.new
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    
    if @topic.save
      redirect_to @topic
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name, :description, :is_active, :is_default, :is_int, :is_string, :is_text, :is_float, :is_duration, :is_boolean, :min_scale, :max_scale, :is_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DearDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with model: [ @topic, @log ] do |f| %>
  <h4><%= @topic.description %></h4>

  <% if @topic.is_text %>
    <div>
      <%= f.text_field :as_text %>
    </div>
  <% end %>

  <% if @topic.is_int %>
    <div>
      <%= f.number_field :as_int %>
    </div>
  <% end %>

  <% if @topic.is_string %>
    <div>
      <%= f.text_field :as_string %>
    </div>
  <% end %>

  <% if @topic.is_float %>
    <div>
      <%= f.number_field :as_float %>
    </div>
  <% end %>

  <% if @topic.is_duration %>
    <div>
      <%= f.number_field :as_duration %>
    </div>
  <% end %>

  <% if @topic.is_boolean %>
    <div>
      <%= f.check_box :as_boolean %>
    </div>
  <% end %>

  <% if @topic.is_list %>
    <div>
      <%= f.text_field :as_list %>
    </div>
  <% end %>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/new.html.erb
<small><%= link_to "Topics", topics_path %></small>
<h2>Log A <%= @topic.name.titleize %></h2>
<%= render "form", topic: @topic, log: @log %>

app/views/pages/about.html.erb
<h1>Welcome to Dear Diary</h1>
<ul>
  <li><%= link_to "Your Topics", topics_path %></li>
</ul>

app/views/topics/_form.html.erb
<%= form_with model: topic do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <% topic.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :is_active %>
    <%= f.check_box :is_active%>
  </div>
  <div>
    <%= f.label :is_default %>
    <%= f.check_box :is_default %>
  </div>
  <div>
    <%= f.label :is_string %>
    <%= f.check_box :is_string %>
  </div>
  <div>
    <%= f.label :is_text %>
    <%= f.check_box :is_text %>
  </div>
  <div>
    <%= f.label :is_float %>
    <%= f.check_box :is_float %>
  </div>
  <div>
    <%= f.label :is_duration %>
    <%= f.check_box :is_duration %>
  </div>
  <div>
    <%= f.label :is_boolean %>
    <%= f.check_box :is_boolean %>
  </div>
  <div>
    <%= f.label :is_list %>
    <%= f.check_box :is_list %>
  </div>
  <div>
    <%= f.label :is_int %>
    <%= f.check_box :is_int %>
  </div>
  <div>
    <%= f.label :min_scale %>
    <%= f.number_field :min_scale %>
  </div>
  <div>
    <%= f.label :max_scale %>
    <%= f.number_field :max_scale %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<small><%= link_to "Back", topic_path(@topic) %></small>
<h2>Edit</h2>
<%= render "form", topic: @topic %>

app/views/topics/index.html.erb
<small><%= link_to "Home", root_path %></small>
<hr>
<small><%= link_to "+ Create", new_topic_path(@topic) %></small>
<h2>Topics</h1>
<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.name, topic %> → </li>
  <% end %>
</ul>

app/views/topics/new.html.erb
<small><%= link_to "Back", topics_path %></small>
<h2>Create new topic</h2>
<%= render "form", topic: @topic %>

app/views/topics/show.html.erb
<small><%= link_to "Back", topics_path %></small>
<hr>

<h2><%= @topic.name %></h2>
<small><%= link_to "Edit", edit_topic_path(@topic) %></small><br>
<hr>

<h4>Configure fields:</h4>
<p>Description: <%= @topic.description %></p>
<p>Active: <%= @topic.is_active ? "✅" : "-" %></p>
<p>Default: <%= @topic.is_default ? "✅" : "-" %></p>
<p>String: <%= @topic.is_string ? "✅" : "-" %></p>
<p>Text: <%= @topic.is_text ? "✅" : "-" %></p>
<p>Float: <%= @topic.is_float ? "✅" : "-" %></p>
<p>Duration: <%= @topic.is_duration ? "✅" : "-" %></p>
<p>Boolean: <%= @topic.is_boolean ? "✅" : "-" %></p>
<p>List: <%= @topic.is_list ? "✅" : "-" %></p>
<p>Integer: <%= @topic.is_int ? "✅" : "-" %></p>
<p>Scale: <%= @topic.min_scale %> - <%= @topic.max_scale %></p>

<hr>
<div>
  <h4>Log</h4>
  <%= render "logs/form", topic: @topic, log: @log %>
</div>